# Generated by Django 3.2.4 on 2021-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
<<<<<<< HEAD
         migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
=======
>>>>>>> f5d6cdddc493c836af638f8719be5067ce326c1d
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
<<<<<<< HEAD
        
=======
>>>>>>> f5d6cdddc493c836af638f8719be5067ce326c1d
    ]
