# Generated by Django 3.2.4 on 2021-06-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210620_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_id',
            new_name='id',
        ),
    ]
