# Generated by Django 3.2.4 on 2021-07-05 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_todo_overduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='overdueDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
