# Generated by Django 3.2.4 on 2021-07-05 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_todo_overduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='overdueDate',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 17, 4, 18, 164634)),
        ),
    ]
