# Generated by Django 3.2.4 on 2021-07-05 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_alter_todo_overduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='overdueDate',
            field=models.DateField(default=datetime.date(2021, 7, 5)),
        ),
    ]
