# Generated by Django 3.2.4 on 2021-07-05 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_alter_todo_overduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='overdueDate',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 13, 4, 5, 575035, tzinfo=utc)),
        ),
    ]
