# Generated by Django 3.2.4 on 2021-07-05 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_alter_todo_overduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='overdueDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
